"""add_password_reset_fields

Revision ID: bed781fc7b46
Revises: d068b3f02ade
Create Date: 2025-09-10 18:35:12.588875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bed781fc7b46'
down_revision = 'd068b3f02ade'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'is_featured',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('products', 'is_top_product',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('users', sa.Column('reset_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_reset_token'), 'users', ['reset_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_reset_token'), table_name='users')
    op.drop_column('users', 'reset_token_expires')
    op.drop_column('users', 'reset_token')
    op.alter_column('products', 'is_top_product',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('products', 'is_featured',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
