"""add_featured_and_top_product_fields

Revision ID: d068b3f02ade
Revises: ee51c411287c
Create Date: 2025-09-10 16:54:43.325464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd068b3f02ade'
down_revision = 'ee51c411287c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_featured', sa.Boolean(), nullable=True, default=False))
    op.add_column('products', sa.Column('is_top_product', sa.Boolean(), nullable=True, default=False))
    
    # Set default values for existing records
    op.execute("UPDATE products SET is_featured = false WHERE is_featured IS NULL")
    op.execute("UPDATE products SET is_top_product = false WHERE is_top_product IS NULL")
    
    # Make columns non-nullable
    op.alter_column('products', 'is_featured', nullable=False)
    op.alter_column('products', 'is_top_product', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_top_product')
    op.drop_column('products', 'is_featured')
    # ### end Alembic commands ###
