"""add_sort_order_to_categories

Revision ID: ee51c411287c
Revises: 23dc8648ac2c
Create Date: 2025-09-10 16:08:18.755955

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ee51c411287c'
down_revision = '23dc8648ac2c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add sort_order column as nullable first
    op.add_column('categories', sa.Column('sort_order', sa.Integer(), nullable=True))
    
    # Set default values for existing categories based on their current order
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE categories 
        SET sort_order = subquery.row_number - 1
        FROM (
            SELECT id, ROW_NUMBER() OVER (ORDER BY id) as row_number
            FROM categories
        ) AS subquery
        WHERE categories.id = subquery.id
    """))
    
    # Now make the column not nullable
    op.alter_column('categories', 'sort_order', nullable=False)
    
    op.alter_column('product_variants', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.drop_index('idx_product_variants_active', table_name='product_variants')
    op.drop_index('idx_product_variants_product_id', table_name='product_variants')
    op.drop_column('products', 'specifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('specifications', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index('idx_product_variants_product_id', 'product_variants', ['product_id'], unique=False)
    op.create_index('idx_product_variants_active', 'product_variants', ['is_active'], unique=False)
    op.alter_column('product_variants', 'price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('categories', 'sort_order')
    # ### end Alembic commands ###
