"""add_user_address_fields

Revision ID: f382e7e3ecfa
Revises: bed781fc7b46
Create Date: 2025-09-10 20:20:06.120304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f382e7e3ecfa'
down_revision = 'bed781fc7b46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('entity_type', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('tax_id', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('company_name', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('trade_register_no', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('bank_name', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('iban', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('county', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('address', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'address')
    op.drop_column('users', 'city')
    op.drop_column('users', 'county')
    op.drop_column('users', 'iban')
    op.drop_column('users', 'bank_name')
    op.drop_column('users', 'trade_register_no')
    op.drop_column('users', 'company_name')
    op.drop_column('users', 'tax_id')
    op.drop_column('users', 'entity_type')
    # ### end Alembic commands ###
